### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by wsilverio** [plomoplomolab/plomoplomolab.github.io#1]
- [ ] PAINEO
- [ ] Librenaria Hardware
- [ ] Librenaria Softwre
- [ ] Neopira
- [ ] Dojo Shield v0, v1
- [ ] Livro Karpem
- [ ] Livro Alicia
- [ ] sisPET
- [ ] Chronos tweet
- [ ] Chronos email
- [ ] P5 sketches (youtube, exp-P5)
- [ ] minicurso Arduino Wakeup
- [ ] minicurso Arduino/P5 Algures X
- [ ] Oficinas dos Calouros PET
- [ ] Scratch Day
- [ ] Ocupação Digital
- [ ] Mesa de Bolinhas
- [ ] Jardim de luzes
- [ ] Chuva de luzes
- [ ] Loteria VHDL
- [ ] Bici430
- [ ] opticalPX4Flow-Viewer
